### ISSUE TITLE
gf-challenge-id

### ISSUE THREAD

**Issue by Eless54** [zakuciael/ez-captcha#1]
gf-challenge-id is not yet available on "https://spark.gameforge.com/api/v1/auth/sessions" header

**Comment by zakuciael** [comment]
> gf-challenge-id is not yet available on "https://spark.gameforge.com/api/v1/auth/sessions" header

What do you mean by "is not yet available"?

**Comment by Eless54** [comment]
gf-challenge-id is not available anymore on "https://spark.gameforge.com/api/v1/auth/sessions" header
-> Sorry traduction mistake

**Comment by zakuciael** [comment]
`gf-challenge-id` is still present in the login request, and it is accompanied by the `409 Conflict` status code.
