### ISSUE TITLE
login never define

### ISSUE THREAD

**Issue by Eless54** [zakuciael/ez-captcha#2]
https://github.com/zakuciael/ez-captcha/blob/fe9ab1ab9cdbd14484f17556f13df52d715c1f3a/src/index.ts#L43
Ur login function is never define

**Comment by zakuciael** [comment]
https://github.com/zakuciael/ez-captcha/blob/fe9ab1ab9cdbd14484f17556f13df52d715c1f3a/src/index.ts#L15
Login method needs to be provided by the user.
